package services

import (
	"fmt"

	"github.com/joaodeluchi/ms-users/application/repositories"
	"github.com/joaodeluchi/ms-users/domain"
)

type IUserService interface {
	CreateUser(user domain.User) error
	GetUser(userID string) (domain.User, error)
	UpdateUserRoles(userID string, roles []string) error
	DeleteUser(userID string) error
}

type UserService struct {
	UserRepository repositories.UserRepository
}

// id is autogenerated, name can be repeated, i made the validation of unique_user here using the email
func (us UserService) CreateUser(user domain.User) error {
	u, _ := us.UserRepository.FindByEmail(user.Email)

	if u.ID != "" {
		return fmt.Errorf("user already exist")
	}

	if err := user.Validate(); err != nil {
		return err
	}

	_, err := us.UserRepository.Insert(&user)

	if err != nil {
		return err
	}

	return nil
}

func (us UserService) GetUser(userID string) (domain.User, error) {
	user, err := us.UserRepository.GetAll(userID)

	if err != nil {
		return domain.User{}, err
	}

	return *user, err
}

func (us UserService) UpdateUserRoles(userID string, roles []domain.Role) error {
	user, err := us.UserRepository.GetAll(userID)

	if err != nil {
		return err
	}

	user.Roles = roles

	_, err = us.UserRepository.Update(user)

	if err != nil {
		return err
	}

	return nil
}

// we never delete an user, we just desactivate
func (us UserService) DeleteUser(userID string) error {
	user, err := us.UserRepository.FindById(userID)
	if err != nil {
		return err
	}

	user.IsActive = false

	_, err = us.UserRepository.Update(user)
	if err != nil {
		return err
	}

	return nil
}

func NewUserService(userRepo repositories.UserRepository) UserService {
	return UserService{
		UserRepository: userRepo,
	}
}
